apache/shardingsphere-on-cloud

README.md
Add links for `make`, `git`, `kubernetes` and `kubebuilder`. Fix #38
=> chore(doc): fix links in readme

README.md, charts/shardingsphere-cluster/values.yaml, charts/shardingsphere-proxy/Chart.yaml, charts/shardingsphere-proxy/values.yaml, doc/shardingsphere-helm-charts.md, doc/shardingsphere-operator.md
Update docs and charts to version 5.2.0, including:
- ShardingSphere Proxy Helm Charts and docs
-  ShardingSphere Cluster(for Operator) default Helm Charts and docs
- README
=> update charts and doc to version 5.2.0

.github/workflows/integration.yml
Currently the procedure is:
- Setup a Kind cluster
- Prepare Helm tools
- Installing ShardingSphere Proxy and Zookeeper with commands provided by the document
- Setup a local MySQL instance
- Connect with ShardingSphere Service and run some basic statements
=> chore(ci): add basic integration test for ShardingSphere Proxy Helm Charts

shardingsphere-operator/build/Dockerfile, shardingsphere-operator/cmd/shardingsphere-operator/main.go, shardingsphere-operator/cmd/shardingsphere-operator/manager/manager.go, shardingsphere-operator/pkg/metrics/metrics.go
In order to monitor the operator, we need to know on which pod the leader is running, this PR provides `shardingsphere_proxy_operator_runtime_is_leader` metric.
=> Feat(operator): add isLeader metric for operator 

charts/apache-shardingsphere-operator-charts/README.md, charts/apache-shardingsphere-operator-charts/values.yaml, docs/content/operation-guide/operator/_index.cn.md, docs/content/operation-guide/operator/_index.en.md, docs/shardingsphere-operator.md
* Change helm charts of shardingsphere operator default image from ghcr hosted to Dockerhub hosted `apache/shardingsphere-operator`
=> chore: update operator charts default image from ghcr to dockerhub

.github/workflows/buildx.yml, .github/workflows/operator-integration.yml, .github/workflows/proxy-integration.yml
Fix:
- Remove `on push` condition in buildx ci
- Proxy Charts IT: install kind and helm instead of using other org's action
- Operator Charts IT: install kind and helm instead of using other org's action
=> fix(ci): fix proxy charts and operator charts IT failure caused by untrusted github action

shardingsphere-operator/pkg/reconcile/common/container.go, shardingsphere-operator/pkg/reconcile/common/container_test.go, shardingsphere-operator/pkg/reconcile/computenode/deployment.go, shardingsphere-operator/pkg/reconcile/computenode/deployment_test.go
=> Common builder

shardingsphere-operator/pkg/controllers/compute_node_controller.go, shardingsphere-operator/pkg/reconcile/common/configmap.go, shardingsphere-operator/pkg/reconcile/computenode/configmap.go, shardingsphere-operator/pkg/reconcile/computenode/configmap_test.go
=> refactor reconcile/configmap to common pkg

shardingsphere-operator/api/v1alpha1/shardingsphere_chaos_types.go, shardingsphere-operator/build/tools/Dockerfile, shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go, shardingsphere-operator/pkg/controllers/shardingsphere_chaos_controller.go, shardingsphere-operator/pkg/reconcile/shardingspherechaos/chaos-mesh.go, shardingsphere-operator/pkg/reconcile/shardingspherechaos/job.go
=> add event and status.phase to control resource create check

shardingsphere-operator/pkg/controllers/shardingsphere_chaos_controller.go, shardingsphere-operator/pkg/kubernetes/chaosmesh/builder.go, shardingsphere-operator/pkg/kubernetes/chaosmesh/chaosmesh.go
Delete chaos resource by finalizer, remove ownreference.
#272
=> refactor(operator): change chaos deletion to finalizer rather than ownreference

shardingsphere-operator/api/v1alpha1/storage_node_types.go, shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go, shardingsphere-operator/pkg/controllers/storage_ndoe_controller_test.go, shardingsphere-operator/pkg/controllers/storage_node_controller.go, shardingsphere-operator/pkg/reconcile/storagenode/aws/rdsinstance.go, shardingsphere-operator/test/e2e/storage_node_controller_test.go
- fix the bug about update status failed coz resource be modified, now we move all update status logic on the top of reconcile func.
- use `slices.Contains` and `slices.Filter` to replace our own `containsString` and 'removeString`.
- fix reconciler event recorder error.
- refactor test cases of testing `delete storage node`.
- fix bug of storage node will be reconciled if it is deleting (with finalizer), if storage node be deleting, we don't need to reconcile any resource anymore.
=> refactor(storage-node): refactor delete storage node logic

.gitignore, pitr/cli/go.mod, pitr/cli/go.sum, pitr/cli/internal/pkg/shardingsphere-proxy.go, pitr/cli/internal/pkg/shardingsphere-proxy_test.go
If there's some quotation marks in metadata, import metadata into sharingsphere may failed.
ShardingSphere now support export metadata encoded by base64: https://github.com/apache/shardingsphere/pull/25691
Decode metadata when export from shardingsphere and save to local, and encode metadta from local  when import metadata.
=> fix(pitr): fix pitr restore metadata failed

examples/operator/shardingsphereproxy-storagenode-aws-rds-instance.yaml, shardingsphere-operator/pkg/controllers/storage_ndoe_controller_test.go, shardingsphere-operator/pkg/controllers/storage_node_controller.go
Refactor `StorageNode` finalize
Now in finalize, if not is marked delete, we will set `StorageNode.Status.Phase` to `Deleting` to MAKE SURE our `StorageNode` will be deleted.  we don't need to set `Deleting` status based on rds instances status.
We will still try to sync rds instance status if it is exits. 
If in `Deleting` phase and all instance are deleted, we will mark phase to `DeleteComplete`, and remove `finalizer` in next reconcile.
=> refactor(storage-node): refatcor finalize logic

shardingsphere-operator/pkg/controllers/storage_ndoe_controller_test.go, shardingsphere-operator/pkg/controllers/storage_node_controller.go, shardingsphere-operator/pkg/shardingsphere/shardingsphere.go, shardingsphere-operator/test/e2e/storage_node_controller_test.go
Unregister storage unit in shardingsphere If `StorageNode` is `Registered` when it been deleted.
**DISCUSS**: should we reconcile the req if unregister failed?
=> feat(storage-node): unregister storage unit when storage node be deleted

shardingsphere-operator/pkg/controllers/storage_ndoe_controller_test.go, shardingsphere-operator/pkg/controllers/storage_node_controller.go
fix https://github.com/apache/shardingsphere-on-cloud/issues/292#issuecomment-1563924644 - the first point
=> fix(storage-node): fix get username and password from dbClass

shardingsphere-operator/Makefile, shardingsphere-operator/pkg/kubernetes/chaosmesh/mocks/store.go
=> feat(operator): add mockgen cmd to makefile

shardingsphere-operator/api/v1alpha1/chaos_types.go, shardingsphere-operator/pkg/controllers/chaos_controller.go, shardingsphere-operator/pkg/kubernetes/chaosmesh/builder.go
=> refactor(operator): refactor network chaos in Chaos reconciliation

shardingsphere-operator/api/v1alpha1/chaos_types.go, shardingsphere-operator/pkg/controllers/chaos_controller.go, shardingsphere-operator/pkg/kubernetes/chaosmesh/builder.go, shardingsphere-operator/pkg/kubernetes/chaosmesh/chaosmesh.go, shardingsphere-operator/pkg/kubernetes/chaosmesh/mocks/store.go
=> fix(operator): fix cpu stress and memory stress builder

charts/apache-shardingsphere-operator-charts/templates/operator_rbac.yaml, shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go, shardingsphere-operator/pkg/controllers/storage_ndoe_controller_test.go, shardingsphere-operator/pkg/controllers/storage_node_controller.go, shardingsphere-operator/test/e2e/e2e_suite_test.go, shardingsphere-operator/test/e2e/storage_node_controller_test.go
- Fix operator may set wrong params when reconcile different storage nodes, coz operator set aws rds client once when start up.
- Typo fix
=> fix: fix storagenode controller may reset params when reconcile aws rds

shardingsphere-operator/pkg/kubernetes/deployment/builder.go, shardingsphere-operator/pkg/kubernetes/deployment/deployment_test.go, shardingsphere-operator/pkg/kubernetes/pod/builder.go, shardingsphere-operator/pkg/kubernetes/pod/pod.go, shardingsphere-operator/pkg/kubernetes/pod/pod_test.go
=> refactor(operator): introduce PodBuilder and ShardingSphereDeploymentBuilder

shardingsphere-operator/pkg/kubernetes/cloudnative-pg/builder.go
=> feat: add cnpg builder cluster parameters

shardingsphere-operator/go.mod, shardingsphere-operator/go.sum, shardingsphere-operator/pkg/controllers/compute_node_controller.go, shardingsphere-operator/pkg/kubernetes/helpers.go, shardingsphere-operator/pkg/kubernetes/helpers_test.go, shardingsphere-operator/pkg/reconcile/computenode/deployment.go
=> feat(operator): introduce SemVer helpers to ComputeNode

pitr/README.md
=> docs: polish pitr README.md

pitr/cli/internal/cmd/backup.go, pitr/cli/internal/cmd/backup_test.go, pitr/cli/internal/pkg/agent-server.go, pitr/cli/internal/pkg/model/const.go
* Should use req.Body to makeup request body
* Should use a common response data type for possible response handling
=> fix: fix checkstatus post req and resp body

pitr/agent/internal/handler/backup.go
=> fix: fix threadsNum in AsyncBackup while handle backup

pitr/cli/internal/cmd/backup.go, pitr/cli/internal/cmd/backup_test.go, pitr/cli/internal/cmd/common.go, pitr/cli/internal/cmd/delete.go, pitr/cli/internal/cmd/delete_test.go, pitr/cli/internal/cmd/restore.go, pitr/cli/internal/cmd/restore_test.go, pitr/cli/internal/cmd/root.go, pitr/cli/internal/cmd/root_test.go, pitr/cli/pkg/promptutil/prompt.go
=> refactor: refactor common functions and command prompt

pitr/cli/internal/cmd/backup.go, pitr/cli/internal/cmd/backup_test.go
- Reduce unnecessary log messages while the backup is cancelled.
=> refactor: optimize backup return message while cancelled

pitr/cli/internal/cmd/backup.go, pitr/cli/internal/cmd/backup_test.go, pitr/cli/pkg/prettyoutput/progress.go
- Abstract a PrettyPrinter to print progress
=> refactor: add PrettyPrinter to print backup progress

pitr/agent/internal/handler/backup.go
Using `gs_probackup init` to init `dn-backup-path` before AddInstance
=> feat: add Init before AddInstance while backing up

pitr/agent/internal/pkg/opengauss.go
It should skip the `gs_probackup init` if the backup path is existed.
=> fix: init will not return err if path exists

pitr/cli/internal/cmd/restore.go
Remove all existing databases in ShardingSphere Proxy before executing pitr restore.
=> feat: remove all databases in proxy before restore
