apache/shardingsphere-on-cloud

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/request_help.yaml
.github/PULL_REQUEST_TEMPLATE
CODE_OF_CONDUCT.md

add PR && ISSUE && REQUEST template

ADD: PR && ISSUE && REQUEST template

---

doc/quickStart.md
shardingsphere-operator/api/v1alpha1/serverconfig.go
shardingsphere-operator/charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxyconfigs.yaml
shardingsphere-operator/charts/shardingsphere-operator/values.yaml

- [*] New feature provided
- feat(doc): add some Annotation, update quick start doc

feat(doc): add some Annotation, update quick start doc

---

README.md

- [*] New feature provided
- feat(doc): add quick start doc connect to README.md

feat(doc): add quick start doc connect to README.md

---

.github/workflows/build.yaml
.github/workflows/check-license.yml
.licenserc.yaml
charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxies.yaml
charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxyconfigs.yaml
shardingsphere-operator/build/Dockerfile

close #10 
- add a ci for build image to github package
- add a ci for check license

feat(ci): add image build && check license ci 

---

.github/workflows/helm-release.yaml

- add a ci to auto release helm

feat(ci): add a new ci to auto release helm 

---

.github/workflows/build.yaml
.github/workflows/check-license.yml
.licenserc.yaml
charts/shardingsphere-cluster/Chart.yaml
charts/shardingsphere-cluster/templates/shardingsphere_v1alpha1_proxy.yaml
charts/shardingsphere-cluster/templates/shardingsphere_v1alpha1_proxyconfig.yaml
charts/shardingsphere-cluster/values.yaml
charts/shardingsphere-operator/Chart.yaml
charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxies.yaml
charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxyconfigs.yaml
charts/shardingsphere-operator/templates/deployment.yaml
charts/shardingsphere-operator/templates/rbac.yaml
charts/shardingsphere-operator/templates/webhook/admission-webhook-apiservice.yaml
charts/shardingsphere-operator/templates/webhook/admission-webhook-configuration.yaml
charts/shardingsphere-operator/templates/webhook/admission-webhook-service.yaml
charts/shardingsphere-operator/values.yaml
shardingsphere-operator/api/v1alpha1/groupversion_info.go
shardingsphere-operator/api/v1alpha1/proxy_status.go
shardingsphere-operator/api/v1alpha1/proxy_types.go
shardingsphere-operator/api/v1alpha1/proxy_webhook.go
shardingsphere-operator/api/v1alpha1/proxyconfig_types.go
shardingsphere-operator/api/v1alpha1/serverconfig.go
shardingsphere-operator/api/v1alpha1/webhook_suite_test.go
shardingsphere-operator/main.go
shardingsphere-operator/pkg/controllers/proxy_controller.go
shardingsphere-operator/pkg/controllers/proxyconfig_controller.go
shardingsphere-operator/pkg/controllers/suite_test.go
shardingsphere-operator/pkg/reconcile/resource.go
shardingsphere-operator/pkg/reconcile/status.go
shardingsphere-operator/pkg/webhook/webhook.go

fix(license): update license and copyright

---

charts/shardingsphere-cluster/templates/shardingsphere_v1alpha1_proxy.yaml
charts/shardingsphere-cluster/values.yaml
charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxies.yaml
charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_proxyconfigs.yaml
charts/shardingsphere-operator/templates/deployment.yaml
charts/shardingsphere-operator/values.yaml
shardingsphere-operator/api/v1alpha1/proxy_status.go
shardingsphere-operator/api/v1alpha1/proxy_types.go
shardingsphere-operator/api/v1alpha1/proxy_webhook.go
shardingsphere-operator/pkg/controllers/proxy_controller.go
shardingsphere-operator/pkg/reconcile/resource.go

- Added ability to automatically create or delete HPA based on configuration
- Fix helm defaults values

feat(HPA): Added ability to automatically create or delete HPA based on configuration

---

README.md

doc: update README 

---

README.md

doc: fix links

---

index.yaml

feat(helm): release helm

---

.github/workflows/build.yaml
charts/shardingsphere-operator/templates/deployment.yaml
doc/deploy.md

- add an online install in doc 
- fix start command for operator
- add tags auto build images

fix(helm): fix start command for operator

---

charts/shardingsphere-proxy/Chart.yaml
charts/shardingsphere-proxy/LICENSE
charts/shardingsphere-proxy/NOTICE
charts/shardingsphere-proxy/charts/governance/Chart.yaml
charts/shardingsphere-proxy/charts/governance/values.yaml
charts/shardingsphere-proxy/templates/configmap.yaml
charts/shardingsphere-proxy/templates/deployment.yaml
charts/shardingsphere-proxy/templates/service.yaml
charts/shardingsphere-proxy/values.yaml

Add charts for ShardingSphere Proxy, which helps to spin up a ShardingSphere Proxy on any kubernetes environment.

add charts of shardingsphere proxy

---

.asf.yaml

Add @windghoul, @mlycore as collaborators of this repository. The discussion is available at: https://lists.apache.org/thread/0w11vq1hwn0gzh53qrk7yhz3lgq4m241

Add original authors as collaborators

---

CONTRIBUTING.md

related to #38

---

.github/ISSUE_TEMPLATE/bug_report.yaml
charts/shardingsphere-cluster/templates/shardingsphere_v1alpha1_shardingsphereproxy.yaml
charts/shardingsphere-cluster/templates/shardingsphere_v1alpha1_shardingsphereproxyserverconfig.yaml
charts/shardingsphere-operator/crds/shardingsphere.apache.org_shardingsphereproxies.yaml
charts/shardingsphere-operator/crds/shardingsphere.apache.org_shardingsphereproxyserverconfigs.yaml
charts/shardingsphere-operator/templates/rbac.yaml
charts/shardingsphere-operator/templates/webhook/admission-webhook-apiservice.yaml
charts/shardingsphere-operator/templates/webhook/admission-webhook-configuration.yaml
doc/shardingsphere-operator.md
shardingsphere-operator/PROJECT
shardingsphere-operator/api/v1alpha1/groupversion_info.go
shardingsphere-operator/api/v1alpha1/proxy_webhook.go
shardingsphere-operator/go.mod
shardingsphere-operator/go.sum
shardingsphere-operator/main.go
shardingsphere-operator/pkg/controllers/proxy_controller.go
shardingsphere-operator/pkg/controllers/proxyconfig_controller.go
shardingsphere-operator/pkg/webhook/webhook.go

- refactor domain sphere-ex.com to apache.org
- close #44

refactor(domain): refactor domain sphere-ex.com to apache.org

---

charts/shardingsphere-operator/values.yaml
shardingsphere-operator/build/Dockerfile
shardingsphere-operator/pkg/controllers/proxy_controller.go

fix(Reconcile): fix create HPA logic

---

charts/shardingsphere-proxy/values.yaml

- support proxy-frontend-database-protocol-type in props
- close #56

chore(values): support proxy-frontend-database-protocol-type in props

---

.github/workflows/proxy-integration.yml
hack/kubernetes/mysql.yml

Add a basic sharding case for Proxy Helm Chart, t_order sharded with t_order_1 and t_order_2.
The result need more work to be verified.

chore(ci): add basic sharding case framework for Proxy Helm Chart

---

cloudformation/apache-shardingsphere-5.2.0.json

Deployment on AWS is very common in many cases. Providing a CloudFormation Stack Template will help users setup a runnable Apache ShardingSphere Proxy cluster in minutes.

feat(cfn): add AWS CloudFormation Stack Template for ShardingSphere Proxy

---

.github/workflows/operator-integration.yml
.github/workflows/proxy-integration.yml

Fix MySQL action in proxy it workflow and operator it workflow

fix(ci): fix mysql action in proxy and operator it workflow

---

shardingsphere-operator/go.mod
shardingsphere-operator/pkg/reconcile/reconcile_test.go
shardingsphere-operator/pkg/reconcile/status.go

Changes:
- Add unit test for IsRunning
- Add unit test for CountReadyPods
- Fix CountReadyPods in the case that one Pods is ready and another is not ready.

chore(reconcile): add unit test for IsRunning and CountReadyPods

---

shardingsphere-operator/pkg/reconcile/reconcile_test.go
shardingsphere-operator/pkg/reconcile/resource.go

Changes:
- Add unit test for ConstructCascadingDeployment
- Fix nil spec attributions handle

chore(reconcile): add unit test for ConstructCascadingDeployment

---

.github/workflows/unit-test.yml

- feat(codecov): add codecov robot for operator

feat(codecov): add codecov robot for operator

---

charts/shardingsphere-cluster/values.yaml
charts/shardingsphere-proxy/values.yaml

chore(config): change default server config in proxy helm-chart

---

charts/shardingsphere-operator-cluster/Chart.yaml
charts/shardingsphere-proxy/Chart.yaml

Update version and appVersion in charts

---

charts/shardingsphere-operator-cluster/Chart.yaml
charts/shardingsphere-operator/Chart.yaml

Update chart name with apache prefix in Chart.yaml

---

charts/shardingsphere-operator-cluster/values.yaml

- fix default proxy version in operator

fix(version): fix default proxy version in operator

---

charts/shardingsphere-operator-cluster/Chart.yaml
charts/shardingsphere-operator/Chart.yaml
charts/shardingsphere-proxy/Chart.yaml

Update chart name with charts

---

shardingsphere-operator/pkg/reconcile/reconcile_test.go

closes #80 
I would be happy to get a hacktoberfest-accepted label for this pull request.

chore(reconcile): add unit test for UpdateService

---

.asf.yaml

feat(gitpages): add git pages in asf.yaml

---

index.yaml

feat(charts): add index.yaml

---

index.yaml

- update index for release 0.1.0

chore(index): update index for release 0.1.0

---

charts/apache-shardingsphere-operator-charts/README.md
charts/apache-shardingsphere-operator-cluster-charts/README.md
charts/apache-shardingsphere-proxy-charts/README.md

chore(docs): add README.md for charts

---

shardingsphere-operator/build/Dockerfile

fix(build): fix docker build failed

---

charts/apache-shardingsphere-operator-charts/LICENSE
charts/apache-shardingsphere-operator-cluster-charts/LICENSE
charts/apache-shardingsphere-proxy-charts/LICENSE

fix: fix directories in charts LICENSE

---

docs/themes/hugo-theme-learn/layouts/partials/language.html
docs/themes/hugo-theme-learn/layouts/partials/menu.html

1. Remove `download pdf` button.
2. Fix 404 page when switch language.

chore(docs): update docs for layout

---

charts/apache-shardingsphere-operator-charts/values.yaml
charts/apache-shardingsphere-operator-cluster-charts/values.yaml
charts/apache-shardingsphere-proxy-charts/values.yaml
docs/content/operation-guide/helm/_index.cn.md
docs/content/operation-guide/helm/_index.en.md
docs/content/operation-guide/operator/_index.cn.md
docs/content/operation-guide/operator/_index.en.md
docs/shardingsphere-helm-charts.md
docs/shardingsphere-operator.md

- add nameOverride for helm
- update doc

chore(helm,doc): update doc,helm for new version

---

docs/layouts/index.html

Signed-off-by: shardingsphere <dev@shardingsphere.apache.org>
1.  update layout.html.

chore(docs): update layout.html

---

docs/content/operation-guide/cloudformation-multi-az/_index.en.md
docs/content/operation-guide/using-terraform-to-deploy-multi-az/_index.en.md

change Chinese content to English

---

docs/content/best-practices/_index.en.md
docs/content/operation-guide/cloudformation-multi-az/_index.en.md
docs/content/operation-guide/using-terraform-to-deploy-multi-az/_index.en.md

The first version

---

index.yaml

chore(index): update index.yaml for 0.1.1

---

cloudformation/multi-az/cf.rb
cloudformation/multi-az/shardingsphere-cloud-init.yml

There the follwing changes.
1. Updated the value of HealthCheckType from "EC2" to "ELB".
2. Added `ShardingSphereProxyAsgDesiredCapacity`, `ShardingSphereProxyAsgMaxSize`, `ShardingSphereProxyAsgHealthCheckGracePeriod` parameters.
3. Updated from the One `ASG` per AZ to `ASG` contains multiple AZs.
4. Updated restart strategy for shardingsphere.service
Signed-off-by: shardingsphere <dev@shardingsphere.apache.org>

feat(cloudformation): update parameter and cloud-init for cloudformation

---

RELEASE-NOTES.md
charts/apache-shardingsphere-operator-charts/Chart.yaml
charts/apache-shardingsphere-operator-cluster-charts/Chart.yaml
charts/apache-shardingsphere-operator-cluster-charts/values.yaml
charts/apache-shardingsphere-proxy-charts/Chart.yaml
charts/apache-shardingsphere-proxy-charts/values.yaml

0.1.1 release

---

cloudformation/multi-az/cf.rb
cloudformation/multi-az/cfn-hup.conf
cloudformation/multi-az/cfn-hup.service
cloudformation/multi-az/cloudwatch-agent-auto-reloader.conf
cloudformation/multi-az/cloudwatch-agent.json
cloudformation/multi-az/shardingsphere-cloud-init.yml

1. Support using cloudwatch collect `ShardingSphereProxy` logs.

feat(cloudformation): Support using cloudwatch collect `ShardingSphereProxy` logs

---

terraform/main.tf
terraform/shardingsphere/cloud-init.yml
terraform/shardingsphere/main.tf
terraform/shardingsphere/variables.tf

1. Support using cloudwatch collect logs for terraform.

feat(terraform): support using cloudwatch collect logs for terraform

---

cloudformation/multi-az/cloudwatch-agent.json
cloudformation/multi-az/shardingsphere-cloud-init.yml
terraform/amazon/shardingsphere/cloud-init.yml
terraform/huawei/cloud-init.yml

chore(terraform,cloudformation): unified shardingsphere proxy naming

---

terraform/amazon/shardingsphere/cloud-init.yml
terraform/amazon/shardingsphere/main.tf

feat(terraform): Support multi-version configuration of shardingsphere proxy in aws

---

grafana/ShardingSphere-Operator-Runtime-dashboard.json

Add grafana dashboard for shardingsphere-operator controller runtime.

feat(operator): add grafana dashaboard  for shardingsphere-operator's controller runtime

---

.asf.yaml

chore: update project labels

---

.github/workflows/build.yaml

fix(ci): fix docker build for ci

---

index.yaml

chore(index): update index.yaml for 0.1.2

---

NOTICE
RELEASE-NOTES.md
charts/README.md
charts/apache-shardingsphere-operator-charts/Chart.yaml
charts/apache-shardingsphere-operator-charts/NOTICE
charts/apache-shardingsphere-operator-charts/README.md
charts/apache-shardingsphere-operator-charts/values.yaml
charts/apache-shardingsphere-proxy-charts/Chart.yaml
charts/apache-shardingsphere-proxy-charts/NOTICE
charts/apache-shardingsphere-proxy-charts/charts/governance/Chart.yaml
charts/apache-shardingsphere-proxy-charts/values.yaml
docs/content/operation-guide/operator/_index.cn.md
docs/content/operation-guide/operator/_index.en.md
docs/content/operation-guide/using-terraform-to-deploy-multi-az-on-huaweicloud/_index.cn.md
docs/content/operation-guide/using-terraform-to-deploy-multi-az-on-huaweicloud/_index.en.md
terraform/huawei/README.md

0.1.2 release

---

.github/workflows/build.yaml

feat(ci): add manual docker build for ci

---

shardingsphere-operator/api/v1alpha1/proxy_status.go
shardingsphere-operator/api/v1alpha1/zz_generated.deepcopy.go
shardingsphere-operator/pkg/controllers/proxy_controller.go
shardingsphere-operator/pkg/reconcile/deployment.go
shardingsphere-operator/pkg/reconcile/deployment_test.go

Fix wrong readyNodes in some cases, and introduce condition `Deployed` for clusters if any pods are initializing.

fix(operator): fix readyNodes and conditions in ProxyStatus

---

shardingsphere-operator/pkg/reconcile/deployment.go

fix(operator): fix mysqlDriver config and conditions nil error 

---

shardingsphere-operator/pkg/reconcile/computenode/service.go
shardingsphere-operator/pkg/reconcile/computenode/service_test.go

Fix Service NodePort while updating in some cases.

fix: fix service node port error

---

shardingsphere-operator/pkg/reconcile/computenode/deployment.go

fix: fix extra container port

---

shardingsphere-operator/api/v1alpha1/compute_node_types.go
shardingsphere-operator/cmd/shardingsphere-operator/main.go
shardingsphere-operator/cmd/shardingsphere-operator/manager/manager.go
shardingsphere-operator/pkg/controllers/compute_node_controller.go
shardingsphere-operator/pkg/controllers/proxy_controller.go
shardingsphere-operator/pkg/controllers/proxyconfig_controller.go
shardingsphere-operator/pkg/kubernetes/deployment/deployment.go
shardingsphere-operator/pkg/reconcile/computenode/deployment.go
shardingsphere-operator/pkg/reconcile/computenode/deployment_test.go

refactor: using builder to accomplish Deployment creation and update

---

shardingsphere-operator/pkg/controllers/compute_node_controller.go

feat: add nodeport write back to ComputeNode

---

pitr/cli/Makefile
pitr/cli/README.md
pitr/cli/go.mod
pitr/cli/go.sum
pitr/cli/internal/cmd/backup.go
pitr/cli/internal/cmd/resotre.go
pitr/cli/internal/cmd/show.go
pitr/cli/internal/pkg/agent-server.go
pitr/cli/internal/pkg/shardingsphere-proxy.go
pitr/cli/main.go

Initialize the pitr cli client project layout

feat: init pitr cli project

---

pitr/agent/Makefile
pitr/agent/main.go

1. set up and test the HTTPS certificate,
2. refactor the main.go code

feat: Set up and test the HTTPS certificate, and refactor the `main.go` code

---

pitr/agent/main.go
pitr/agent/pkg/cmds/cmd.go
pitr/agent/pkg/cmds/cmd_test.go

Continuous output from the command line.

feat: pitr agent service add shell flags and example for execute command

---

.github/workflows/unit-test.yml
shardingsphere-operator/pkg/reconcile/computenode/compute_node_suite_test.go
shardingsphere-operator/pkg/reconcile/computenode/compute_node_test.go

- Add Envtest for Deployment creation.

chore: introduce envtest for IT

---

pitr/agent/main.go

feat: get shell from env

---

pitr/agent/go.mod
pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/middleware/http_header.go
pitr/agent/internal/handler/middleware/logger.go
pitr/agent/internal/handler/middleware/recovery.go
pitr/agent/internal/handler/middleware/uniform_err_resp.go
pitr/agent/main.go
pitr/agent/pkg/cmds/cmd.go
pitr/agent/pkg/cmds/cmd_test.go
pitr/agent/pkg/responder/resp.go
pitr/agent/pkg/syncutils/recover_func.go
pitr/cli/go.mod

feat: optimize command execution

---

pitr/agent/go.mod
pitr/agent/go.sum
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go
pitr/agent/pkg/cmds/cmd.go
pitr/agent/pkg/cmds/cmd_test.go

feat:wrapping the backup subcommand

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/model/backup.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go

feat:add show cmd and update the test case

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go
pitr/agent/pkg/cmds/cmd.go

feat:add delete backup method and capture shell exec status

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go

feat: init instance method and test it

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go

feat: instance add\del method and test it

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go

feat: gs_ctl start|stop and test it

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/pkg/cmds/cmd.go

feat:add restore method and update AsyncExec func

---

pitr/agent/main.go

feat:process pgdata values

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/view/backup.go
pitr/agent/internal/handler/view/restore.go
pitr/agent/internal/handler/view/show.go

feat(pitr): agent server api output

---

shardingsphere-operator/cmd/shardingsphere-operator/manager/manager.go
shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go

- Using FeatureGateHandler to handle different experimental features.

feat: update FeatureGate handlers

---

charts/apache-shardingsphere-operator-charts/crds/shardingsphere.apache.org_computenodes.yaml
shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go

fix(operator): fix commandline options parse for feature gates

---

pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go

feat(pitr):agent server,show backup list

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/show.go
pitr/agent/internal/handler/view/show.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/pkg.go
pitr/agent/main.go
pitr/agent/pkg/cmds/cmd.go
pitr/agent/pkg/gsutil/conn.go
pitr/agent/pkg/gsutil/conn_test.go

feat(pitr):complete agent show and show list api

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/backup.go
pitr/agent/internal/handler/view/backup.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go
pitr/agent/internal/pkg/pkg.go
pitr/agent/main.go

feat(pitr):agent backup api

---

.gitignore
pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/restore.go
pitr/agent/internal/handler/show.go
pitr/agent/internal/handler/view/show.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/main.go
pitr/agent/pkg/cmds/cmd.go

feat(pitr):agent restore api

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go

feat(pitr):add gs_ctl func for IOpenGauss

---

pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/restore.go
pitr/agent/internal/pkg/opengauss.go
pitr/agent/main.go

feat(pitr):agent restore api and backup pgdata

---

pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go
pitr/agent/internal/pkg/pkg.go
pitr/agent/internal/pkg/pkg_test.go
pitr/agent/main.go

chore(agent): add debug log

---

charts/apache-shardingsphere-operator-charts/values.yaml

Fix operator tag: from 0.1.2 to 0.2.0

fix(helm): version tag: from 0.1.2 to 0.2.0

---

pitr/cli/internal/pkg/agent-server.go
pitr/cli/internal/pkg/agent-server_test.go
pitr/cli/internal/pkg/model/as_restore.go
pitr/cli/internal/pkg/model/as_show.go

feat(pitr):cli-agent api integration

---

pitr/cli/internal/pkg/local-storage.go
pitr/cli/internal/pkg/local-storage_test.go
pitr/cli/internal/pkg/model/ls_backup.go
pitr/cli/internal/pkg/xerr/err.go

feat(pitr):local storage,add some query method

---

pitr/cli/internal/pkg/local-storage_test.go
pitr/cli/internal/pkg/model/ls_backup.go
pitr/cli/internal/pkg/model/ss_backup.go
pitr/cli/internal/pkg/shardingsphere-proxy.go
pitr/cli/internal/pkg/shardingsphere-proxy_test.go

feat(pitr):wrap ShardingSphere Proxy DistSQL

---

shardingsphere-operator/pkg/controllers/compute_node_controller.go

fix(operator): fix update loop while handle status

---

charts/apache-shardingsphere-operator-charts/templates/operator_deployment.yaml

check helm values when install operator by helm.
If values enable zookeeper's persistence, will warning user to set a correct storageClass to make sure zookeeper will running in normal.

chore(operator): add some check when install operator by helm

---

shardingsphere-operator/cmd/shardingsphere-operator/manager/manager.go
shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go
shardingsphere-operator/cmd/shardingsphere-operator/manager/option_test.go
shardingsphere-operator/pkg/controllers/compute_node_controller.go

Refactor ComputeNode controller for better maintainability

refactor(operator): refactor ComputeNode controller

---

shardingsphere-operator/pkg/distsql/visitor/rdl_visitor.go

chore(encrypt-distsql): Add IfExists to AST

---

shardingsphere-operator/pkg/distsql/ast/rdl_ast.go
shardingsphere-operator/pkg/distsql/visitor/distsql_test.go
shardingsphere-operator/pkg/distsql/visitor/rdl_visitor.go
shardingsphere-operator/pkg/distsql/visitor/visitor_suite_test.go

feat: Add covert AST to string method

---

shardingsphere-operator/pkg/distsql/ast/rdl_ast.go
shardingsphere-operator/pkg/distsql/visitor/rdl_visitor.go

feat: support alter & drop encrypt rule distsql AST

---

.github/workflows/pitr-unit-test.yml
pitr/agent/internal/pkg/opengauss.go
pitr/agent/internal/pkg/opengauss_test.go
pitr/agent/internal/pkg/pkg_test.go
pitr/agent/main.go
pitr/agent/pkg/cmds/cmd_test.go
pitr/agent/pkg/cmds/cmds_test.go
pitr/agent/pkg/gsutil/conn_test.go
pitr/agent/pkg/logging/log.go

chore(pitr): pitr agent add test workflow

---

.licenserc.yaml
pitr/agent/internal/cons/error.go
pitr/agent/internal/handler/diskspace.go
pitr/agent/internal/handler/diskspace_test.go
pitr/agent/internal/handler/handler_suite_test.go
pitr/agent/internal/handler/view/diskspace.go
pitr/agent/main.go
pitr/cli/internal/cmd/backup.go
pitr/cli/internal/cmd/backup_test.go
pitr/cli/internal/cmd/cmd_suite_test.go
pitr/cli/internal/cmd/restore.go
pitr/cli/internal/cmd/restore_test.go
pitr/cli/internal/cmd/root.go
pitr/cli/internal/cmd/root_test.go
pitr/cli/internal/pkg/agent-server.go
pitr/cli/internal/pkg/mocks/agent-server.go
pitr/cli/internal/pkg/model/as_show.go

- `pitr agent` support `api/diskspace` to get local disk space info.
- `pitr cli` support to print all storage nodes disk space info before do backup and restore, and need User to approve to exec tasks.
the whole progress may like this:
```bash
2023-04-25T13:32:40+08:00  info  Checking agent server status...
+---------------------------------+
| Agent Server Status             |
+---+-----------------+-----------+
| # | AGENT SERVER IP | STATUS    |
+---+-----------------+-----------+
| 1 | 127.0.0.1       | Available |
+---+-----------------+-----------+
2023-04-25T13:32:40+08:00  info  Checking disk space...
+--------------------------------------------------------------------------------------+
| Disk Space Status                                                                    | …
```

feat(pitr): pitr support check disk space before do backup and restore

---

pitr/agent/internal/handler/restore.go
pitr/agent/main.go
pitr/cli/internal/cmd/backup.go
pitr/cli/internal/cmd/restore.go
pitr/cli/internal/cmd/restore_test.go
pitr/cli/internal/cmd/root.go
pitr/cli/internal/pkg/model/as_backup.go
pitr/cli/internal/pkg/model/as_restore.go
pitr/cli/internal/pkg/model/const.go
pitr/cli/pkg/prettyoutput/prettyoutput_suite_test.go
pitr/cli/pkg/prettyoutput/progress_test.go

- `restore` support display progress of task and will print result in table format after all task done.
- fix some typo

chore(pitr): restore support display progress

---

shardingsphere-operator/api/v1alpha1/shardingsphere_chaos_types.go
shardingsphere-operator/pkg/controllers/shardingsphere_chaos_controller.go
shardingsphere-operator/pkg/reconcile/shardingspherechaos/configmap.go
shardingsphere-operator/pkg/reconcile/shardingspherechaos/job.go
shardingsphere-operator/pkg/reconcile/shardingspherechaos/sahrdingsphere_chaos.go

fix(operator): fix configmap and job creation error while no shardingspherechaos is found

---

shardingsphere-operator/api/v1alpha1/compute_node_types.go
shardingsphere-operator/pkg/kubernetes/configmap/builder.go
shardingsphere-operator/pkg/kubernetes/configmap/configmap.go
shardingsphere-operator/pkg/kubernetes/configmap/configmap_suite_test.go
shardingsphere-operator/pkg/kubernetes/configmap/configmap_test.go
shardingsphere-operator/pkg/kubernetes/deployment/builder.go

refactor(operator): refactor configmap build serverconfig and tests

---

shardingsphere-operator/api/v1alpha1/storage_node_types.go
shardingsphere-operator/pkg/controllers/storage_node_controller.go
shardingsphere-operator/pkg/reconcile/storagenode/aws/aurora.go
shardingsphere-operator/pkg/reconcile/storagenode/aws/aws.go
shardingsphere-operator/pkg/reconcile/storagenode/aws/mocks/aws.go
shardingsphere-operator/pkg/reconcile/storagenode/aws/rdsinstance.go
shardingsphere-operator/pkg/reconcile/storagenode/aws/rdsinstance_test.go

add finalize logic, update computeDesiredState logic

feat(storage-node): add finalize logic

---

.github/labeler.yml
.github/workflows/labeler.yml

add github action [labeler](https://github.com/actions/labeler), this action will auto add label based on files changed in a PR.
now supported labels:
- `github-action`
- `operator`
- `pitr`
- `cloudformation`
- `terraform`
- `docs`
- `helm`
- `grafana`
- `wasm`

add auto labeler github action

---

examples/operator/shardingsphereproxy-storagenode-aws-rds-instance.yaml

Add an example yaml file for setup a `DatabaseClass` and `StorageNode` CR.
You can use this yaml file to test `StorageNode Controller` follow these steps:
```sh
cd shardingsphere-operator
go run cmd/shardingsphere-operator/main.go --feature-gates=StorageNode=true --aws-region={AWS_REGION} --aws-access-key-id={YOUR_AWS_ACCESS_KEY} --aws-secret-key={YOUR_AWS_SECRET}
kubectl apply -f ../examples/operator/shardingsphereproxy-storagenode-aws-rds-instance.yaml
```

chore(storage-node): add example of storage node

---

charts/apache-shardingsphere-operator-charts/values.yaml
examples/operator/shardingsphereproxy-mysql-cluster.yaml

Fix user value in `charts/apache-shardingsphere-operator-charts/values.yaml` and `examples/operator/shardingsphereproxy-mysql-cluster.yaml`
Make sure ComputeNode's default user is `root`

fix(helm): fix user value

---

shardingsphere-operator/api/v1alpha1/compute_node_types.go
shardingsphere-operator/pkg/kubernetes/deployment/builder.go
shardingsphere-operator/pkg/kubernetes/deployment/deployment_test.go
shardingsphere-operator/pkg/kubernetes/service/buidler.go

Fix: 
* Sync common prometheus annotations from ComputeNode annotations to corresponding Pods and Service
* Sync metrics port from ComputeNode.Spec.Bootstrap to corresponding Service ports
* Add `yaml: xxx,omitempty` tag for ComputeNode.Spec.Bootstrap for export

fix(operator): fix agent metrics annotations and port sync

---

grafana/ShardingSphere-Proxy-Dashboard.json

* Fix legends name in proxy related diagrams..

fix(grafana): fix legends name

---

charts/apache-shardingsphere-proxy-charts/templates/configmap.yaml
charts/apache-shardingsphere-proxy-charts/templates/deployment.yaml

* Fix agent ConfigMap render template in  ShardingSphere Proxy charts.

fix(helm): fix proxy charts agent configmap name template

---

shardingsphere-operator/pkg/controllers/storage_ndoe_controller_test.go
shardingsphere-operator/pkg/controllers/storage_node_controller.go
shardingsphere-operator/pkg/reconcile/storagenode/aws/rdsinstance.go
shardingsphere-operator/pkg/shardingsphere/mocks/shardingsphere.go
shardingsphere-operator/pkg/shardingsphere/shardingsphere.go
shardingsphere-operator/pkg/shardingsphere/shardingsphere_test.go
shardingsphere-operator/test/e2e/storage_node_controller_test.go

Fix database not selected bug.
When register and unregister storage unit, use database first.

fix(storage-node): fix register storage unit bug

---

.github/workflows/buildx.yml
charts/apache-shardingsphere-operator-charts/templates/operator_deployment.yaml
shardingsphere-operator/Makefile
shardingsphere-operator/build/Dockerfile
shardingsphere-operator/start.sh

* Fix github action, add `arm/v8` to docker buildx action 
* Update command in operator charts and remove `command` in Deployment spec
* Update Makefile and use `docker buildx`
* Update operator Dockerfile and remove `chmod`, add `/bin/sh` in ENTRYPOINT

fix(build): fix arm related docker build and github action

---

shardingsphere-operator/api/v1alpha1/compute_node_types.go
shardingsphere-operator/pkg/controllers/compute_node_controller.go
shardingsphere-operator/pkg/reconcile/computenode/compute_node_test.go

* Remove `readyInstances` in ComputeNodeStatus
* Add `replicas` in ComputeNodeStatus to fix `kubectl scale`

refactor(operator): update compute node definition

---

charts/apache-shardingsphere-operator-charts/crds/shardingsphere.apache.org_storagenodes.yaml
charts/apache-shardingsphere-operator-charts/templates/operator_deployment.yaml
charts/apache-shardingsphere-operator-charts/templates/operator_rbac.yaml
charts/apache-shardingsphere-operator-charts/values.yaml
docs/shardingsphere-operator.md
examples/operator/shardingsphereproxy-storagenode-aws-rds-instance.yaml
shardingsphere-operator/build/Dockerfile
shardingsphere-operator/cmd/shardingsphere-operator/manager/manager.go
shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go
shardingsphere-operator/go.mod
shardingsphere-operator/go.sum
shardingsphere-operator/pkg/controllers/compute_node_controller.go
shardingsphere-operator/pkg/controllers/proxy_controller.go
shardingsphere-operator/pkg/controllers/proxyconfig_controller.go
shardingsphere-operator/pkg/controllers/shardingsphere_chaos_controller.go
shardingsphere-operator/pkg/controllers/storage_node_controller.go
shardingsphere-operator/pkg/metrics/metrics.go

- Update operator charts to support `StorageNode` feat, and this feat required the newest operator. So we can use this feat when operator release this new version.

update operator charts support StorageNode

---

pitr/cli/internal/cmd/backup.go

Fix a bug try to delete backup file  when backup failed, if bak file is not created, skip.

fix(pitr): fix lsbackup nil error

---

shardingsphere-operator/pkg/controllers/compute_node_controller.go
shardingsphere-operator/pkg/reconcile/computenode/compute_node.go

* Adding conditions in pending phase, including `Initialized` and `Deployed`.
* Adding `IsNotFound` check in reconcile status.

feat(operator): add conditions in pending phase

---

shardingsphere-operator/api/v1alpha1/shardingsphere_chaos_types.go
shardingsphere-operator/go.sum
shardingsphere-operator/pkg/controllers/shardingsphere_chaos_controller.go
shardingsphere-operator/pkg/kubernetes/chaosmesh/builder.go

add cpu,memory,podkill chaos 
#272

add cpu,memory,podkill chaos

---

shardingsphere-operator/pkg/controllers/storage_node_controller.go
shardingsphere-operator/pkg/kubernetes/cloudnative-pg/cloudnative-pg.go

feat: add CloudNative PG finalize

---

charts/apache-shardingsphere-operator-charts/crds/shardingsphere.apache.org_storagenodes.yaml
examples/operator/shardingsphereproxy-storagenode-aws-rds-cluster.yaml
examples/operator/shardingsphereproxy-storageprovider-aws-rds-cluster.yaml
shardingsphere-operator/api/v1alpha1/storage_node_types.go

- Add usage example of `StorageNode` to apply aws rds cluster.
- Fix `StorageNode` printcolumn error.

feat(operator): add StorageNode usage of aws rds cluster

---

shardingsphere-operator/api/v1alpha1/storage_node_types.go
shardingsphere-operator/cmd/shardingsphere-operator/manager/option.go
shardingsphere-operator/pkg/controllers/storage_node_controller.go

refactor(operator): optimize storage node status in CNPG

---

charts/apache-shardingsphere-operator-charts/templates/operator_rbac.yaml
examples/operator/shardingsphere-storageprovider-aws-rds-instance.yaml
shardingsphere-operator/pkg/kubernetes/deployment/builder.go
shardingsphere-operator/pkg/reconcile/common/container.go

- Add AppendEnv to container builder
- Add correct rbac to operator charts
- Fix rds engine version in storageprovider

refactor(operator): add AppendEnv to container builder

---

.github/workflows/proxy-integration.yml
charts/apache-shardingsphere-operator-charts/templates/operator_rbac.yaml
charts/apache-shardingsphere-proxy-charts/templates/deployment.yaml
charts/apache-shardingsphere-proxy-charts/values.yaml
examples/operator/shardingsphere-storageprovider-aws-rds-instance.yaml
shardingsphere-operator/pkg/kubernetes/deployment/builder.go
shardingsphere-operator/pkg/reconcile/common/container.go

- Adjust deployment template and value for agent in version 5.3.2

fix(charts): adjust deployment template and value for agent

---

shardingsphere-operator/pkg/controllers/auto_scaler_controller.go
shardingsphere-operator/pkg/kubernetes/resources.go
shardingsphere-operator/pkg/kubernetes/vpa/builder.go
shardingsphere-operator/pkg/kubernetes/vpa/vpa.go
shardingsphere-operator/pkg/reconcile/autoscaler/auto_scaler.go
shardingsphere-operator/pkg/reconcile/autoscaler/vpa.go

feat: add vpa for AutoScaler

---

pitr/README.md

doc: add readme for pitr

---

pitr/cli/internal/pkg/agent-server.go

fix: fix checkstatus response code

---

pitr/cli/internal/cmd/backup.go
pitr/cli/internal/cmd/show_test.go
pitr/cli/internal/pkg/local-storage_test.go
pitr/cli/internal/pkg/model/ls_backup.go
pitr/cli/pkg/timeutil/time.go

refactor: optimize backup metadata time format

---

pitr/cli/internal/cmd/common.go
pitr/cli/internal/cmd/delete.go
pitr/cli/internal/cmd/restore.go
pitr/cli/internal/cmd/show.go
pitr/cli/internal/cmd/show_test.go
pitr/cli/internal/pkg/local-storage.go
pitr/cli/internal/pkg/local-storage_test.go
pitr/cli/internal/pkg/mocks/local-storage.go

feat: introduce ReadAllByCSN to local storage

---

pitr/cli/internal/cmd/delete.go
pitr/cli/internal/cmd/restore.go

- Using PrettyPrint to refactor delete
- Using PrettyPrint to refactor restore

refactor: using PrettyPrint to refactor delete and restore backup

---

pitr/agent/internal/handler/diskspace.go
pitr/agent/pkg/cmds/cmd.go

* Add stderr as command execution output
* Create the desired backup path before checking disk volume

fix: create backup path before checking disk
